/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy ast-traverser.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "ast-traverser.h"

void visitListJob(ListJob listjob)
{
  while(listjob  != 0)
  {
    /* Code For ListJob Goes Here */
    visitJob(listjob->job_);
    listjob = listjob->listjob_;
  }
}

void visitInput(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    /* Code for StartInput Goes Here */
    visitListJob(p->u.startInput_.listjob_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void visitJob(Job p)
{
  switch(p->kind)
  {
  case is_FGJob:
    /* Code for FGJob Goes Here */
    visitCommandLine(p->u.fGJob_.commandline_);
    break;
  case is_BGJob:
    /* Code for BGJob Goes Here */
    visitCommandLine(p->u.bGJob_.commandline_);
    break;
  case is_AssignJob:
    /* Code for AssignJob Goes Here */
    visitVariableWord(p->u.assignJob_.variableword_);
    visitCommandLine(p->u.assignJob_.commandline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Job!\n");
    exit(1);
  }
}

void visitCommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_FullCommandLine:
    /* Code for FullCommandLine Goes Here */
    visitCommandPart(p->u.fullCommandLine_.commandpart_);
    visitOptInRedir(p->u.fullCommandLine_.optinredir_);
    visitOptOutRedir(p->u.fullCommandLine_.optoutredir_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandLine!\n");
    exit(1);
  }
}

void visitCommandPart(CommandPart p)
{
  switch(p->kind)
  {
  case is_SingleCommand:
    /* Code for SingleCommand Goes Here */
    visitCommand(p->u.singleCommand_.command_);
    break;
  case is_PipelineCommand:
    /* Code for PipelineCommand Goes Here */
    visitCommand(p->u.pipelineCommand_.command_);
    visitCommandPart(p->u.pipelineCommand_.commandpart_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandPart!\n");
    exit(1);
  }
}

void visitListWord(ListWord listword)
{
  while(listword  != 0)
  {
    /* Code For ListWord Goes Here */
    visitWord(listword->word_);
    listword = listword->listword_;
  }
}

void visitCommand(Command p)
{
  switch(p->kind)
  {
  case is_FullCommand:
    /* Code for FullCommand Goes Here */
    visitListWord(p->u.fullCommand_.listword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Command!\n");
    exit(1);
  }
}

void visitOptInRedir(OptInRedir p)
{
  switch(p->kind)
  {
  case is_NoInRedir:
    /* Code for NoInRedir Goes Here */
    break;
  case is_InRedir:
    /* Code for InRedir Goes Here */
    visitWord(p->u.inRedir_.word_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptInRedir!\n");
    exit(1);
  }
}

void visitOptOutRedir(OptOutRedir p)
{
  switch(p->kind)
  {
  case is_NoOutRedir:
    /* Code for NoOutRedir Goes Here */
    break;
  case is_OutRedir:
    /* Code for OutRedir Goes Here */
    visitWord(p->u.outRedir_.word_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptOutRedir!\n");
    exit(1);
  }
}

void visitWord(Word p)
{
  switch(p->kind)
  {
  case is_PlainWord:
    /* Code for PlainWord Goes Here */
    visitPlainWord(p->u.plainWord_.plainword_);
    break;
  case is_VarWord:
    /* Code for VarWord Goes Here */
    visitVariableWord(p->u.varWord_.variableword_);
    break;
  case is_StringWord:
    /* Code for StringWord Goes Here */
    visitStringWord(p->u.stringWord_.stringword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Word!\n");
    exit(1);
  }
}

void visitPlainWord(PlainWord p)
{
  /* Code for PlainWord Goes Here */
}
void visitVariableWord(VariableWord p)
{
  /* Code for VariableWord Goes Here */
}
void visitStringWord(StringWord p)
{
  /* Code for StringWord Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

