/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef AST-TRAVERSER
#define AST-TRAVERSER
/* You might want to change the above name. */

#include "Absyn.h"


void visitListJob(ListJob p);
void visitInput(Input p);
void visitJob(Job p);
void visitCommandLine(CommandLine p);
void visitCommandPart(CommandPart p);
void visitListWord(ListWord p);
void visitCommand(Command p);
void visitOptInRedir(OptInRedir p);
void visitOptOutRedir(OptOutRedir p);
void visitWord(Word p);

void visitPlainWord(PlainWord p);void visitVariableWord(VariableWord p);void visitStringWord(StringWord p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

