/* File originally generated by the BNF Converter (bnfc 2.9.6.1). */

#include <stdlib.h>
#include <stdio.h>

#include "ast_traverser.h"
#include "jbox_debug.h"

void visitListJob(ListJob listjob)
{
  DPRINT("visiting ListJob");
  while(listjob  != 0)
  {
    /* Code For ListJob Goes Here */
    visitJob(listjob->job_);
    listjob = listjob->listjob_;
  }
}

void visitListShellToken(ListShellToken listshelltoken)
{
  DPRINT("visiting ListShellToken");
  while(listshelltoken  != 0)
  {
    /* Code For ListShellToken Goes Here */
    visitShellToken(listshelltoken->shelltoken_);
    listshelltoken = listshelltoken->listshelltoken_;
  }
}

void visitInput(Input p)
{
  DPRINT("visiting_Input");
  switch(p->kind)
  {
  case is_In:
    /* Code for In Goes Here */
    visitListJob(p->u.in_.listjob_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void visitJob(Job p)
{
  DPRINT("visiting Job");
  switch(p->kind)
  {
  case is_AssigJob:
    /* Code for AssigJob Goes Here */
    DPRINT("is AssigJob");
    visitWordToken(p->u.assigJob_.wordtoken_);
    visitCommandLine(p->u.assigJob_.commandline_);
    break;
  case is_AIChatJob:
    /* Code for AIChatJob Goes Here */
    DPRINT("is AIChatJob");
    visitAIQuery(p->u.aIChatJob_.aiquery_);
    break;
  case is_AIExecJob:
    /* Code for AIExecJob Goes Here */
    DPRINT("is AIExecJob");
    visitAIQuery(p->u.aIExecJob_.aiquery_);
    break;
  case is_FGJob:
    /* Code for FGJob Goes Here */
    DPRINT("is FGJob");
    visitCommandLine(p->u.fGJob_.commandline_);
    break;
  case is_BGJob:
    /* Code for BGJob Goes Here */
    DPRINT("is BGJob");
    visitCommandLine(p->u.bGJob_.commandline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Job!\n");
    exit(1);
  }
}

void visitCommandLine(CommandLine p)
{
  DPRINT("visiting CommandLine");
  switch(p->kind)
  {
  case is_CmdLine:
    /* Code for CmdLine Goes Here */
    visitCommandPart(p->u.cmdLine_.commandpart_);
    visitOptionalInputRedirection(p->u.cmdLine_.optionalinputredirection_);
    visitOptionalOutputRedirection(p->u.cmdLine_.optionaloutputredirection_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandLine!\n");
    exit(1);
  }
}

void visitCommandPart(CommandPart p)
{
  DPRINT("visiting CommandPart");
  switch(p->kind)
  {
  case is_SnglCmd:
    /* Code for SnglCmd Goes Here */
    DPRINT("is SnglCmd");
    visitCommandUnit(p->u.snglCmd_.commandunit_);
    break;
  case is_PipeCmd:
    /* Code for PipeCmd Goes Here */
    DPRINT("is PipeCmd");
    visitCommandUnit(p->u.pipeCmd_.commandunit_);
    visitCommandPart(p->u.pipeCmd_.commandpart_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandPart!\n");
    exit(1);
  }
}

void visitCommandUnit(CommandUnit p)
{
  DPRINT("visiting CommandUnit");
  switch(p->kind)
  {
  case is_CmdUnit:
    /* Code for CmdUnit Goes Here */
    visitListShellToken(p->u.cmdUnit_.listshelltoken_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandUnit!\n");
    exit(1);
  }
}

void visitOptionalInputRedirection(OptionalInputRedirection p)
{
  DPRINT("visiting OptionalInputRedirection");
  switch(p->kind)
  {
  case is_NoInRedir:
    /* Code for NoInRedir Goes Here */
    DPRINT("is NoInRedir");
    break;
  case is_InRedir:
    /* Code for InRedir Goes Here */
    DPRINT("is InRedir");
    visitShellToken(p->u.inRedir_.shelltoken_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptionalInputRedirection!\n");
    exit(1);
  }
}

void visitOptionalOutputRedirection(OptionalOutputRedirection p)
{
  DPRINT("visiting OptionalOutputRedirection");
  switch(p->kind)
  {
  case is_NoOutRedir:
    /* Code for NoOutRedir Goes Here */
    DPRINT("is NoOutRedir");
    break;
  case is_OutRedir:
    /* Code for OutRedir Goes Here */
    DPRINT("is OutRedir");
    visitShellToken(p->u.outRedir_.shelltoken_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptionalOutputRedirection!\n");
    exit(1);
  }
}

char* visitShellToken(ShellToken p)
{
  DPRINT("visiting ShellToken");
  switch(p->kind)
  {
  case is_Var:
    // return the substituted variable value
    DPRINT("is Var");
    char* var_name = p->u.var_.variabletoken_;
    DPRINT("var_name: %s", var_name);
    char* env_value = getenv(p->u.var_.variabletoken_ + 1); //skip '$'
    DPRINT("env_name: %s", var_name);
    return env_value ? strdup(env_value) : strdup("");

  case is_Wrd:
    // return the word
    DPRINT("is Word");
    char* word = strdup(p->u.wrd_.wordtoken_);
    DPRINT("word: %s", word);
    return word;

  case is_Str:
    // return the string with variable substitution
    //TODO: add non-substitution strings ''
    DPRINT("is Str");
    visitStringToken(p->u.str_.stringtoken_);
    return strdup("");

  default:
    fprintf(stderr, "Error: bad kind field when printing ShellToken!\n");
    exit(1);
  }
}

void visitAIQuery(AIQuery p)
{
  DPRINT("visiting AIQuery");
  switch(p->kind)
  {
  case is_FAIQ:
    /* Code for FAIQ Goes Here */
    DPRINT("is FAIQ");
    visitListShellToken(p->u.fAIQ_.listshelltoken_);
    break;
  case is_EAIQ:
    DPRINT("is EAIQ");
    /* Code for EAIQ Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing AIQuery!\n");
    exit(1);
  }
}

void visitWordToken(WordToken p)
{
  /* Code for WordToken Goes Here */
  DPRINT("visiting WordToken");
}
void visitStringToken(StringToken p)
{
  /* Code for StringToken Goes Here */
  DPRINT("visiting StringToken");
}
void visitVariableToken(VariableToken p)
{
  /* Code for VariableToken Goes Here */
  DPRINT("visiting VariableToken");
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

