/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef AST_TRAVERSER
#define AST_TRAVERSER
/* You might want to change the above name. */

#include "Absyn.h"


void visitListJob(ListJob p);
void visitListShellToken(ListShellToken p);
void visitInput(Input p);
void visitJob(Job p);
void visitCommandLine(CommandLine p);
void visitCommandPart(CommandPart p);
void visitCommandUnit(CommandUnit p);
void visitOptionalInputRedirection(OptionalInputRedirection p);
void visitOptionalOutputRedirection(OptionalOutputRedirection p);
char* visitShellToken(ShellToken p);
void visitAIQuery(AIQuery p);

void visitWordToken(WordToken p);void visitStringToken(StringToken p);void visitVariableToken(VariableToken p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

