/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#include <stdlib.h>
#include <stdio.h>
#include <wordexp.h> 

#include "jbox_debug.h"
#include "jshell_ast_interpreter.h"
#include "jshell_ast_helpers.h"

// forward declarations of private functions
void visitListJob(ListJob p);
void visitJob(Job p);
void visitCommandLine(CommandLine p);
void visitCommandPart(CommandPart p);
JshellCmdParams visitCommandUnit(CommandUnit p);
void visitOptionalInputRedirection(OptionalInputRedirection p);
void visitOptionalOutputRedirection(OptionalOutputRedirection p);
int visitListShellToken(ListShellToken p, wordexp_t* word_vector_ptr);
int visitShellToken(ShellToken p, wordexp_t* word_vector_ptr);
int visitExpansionStringToken(ExpansionStringToken p, wordexp_t* word_vector_ptr);
int visitLiteralStringToken(LiteralStringToken p, wordexp_t* word_vector_ptr);
int visitVariableToken(VariableToken p, wordexp_t* word_vector_ptr);
int visitWordToken(WordToken p, wordexp_t* word_vector_ptr);
void visitAIQueryToken(AIQueryToken p);
void visitAIExecToken(AIExecToken p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);


int interpretInput(Input p)
{
  DPRINT("visiting_Input");
  switch(p->kind)
  {
  case is_In:
    /* Code for In Goes Here */
    visitListJob(p->u.in_.listjob_);
    return 0;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}


void visitListJob(ListJob listjob)
{
  DPRINT("visiting ListJob");
  while(listjob  != 0)
  {
    /* Code For ListJob Goes Here */
    visitJob(listjob->job_);
    listjob = listjob->listjob_;
  }
}


void visitJob(Job p)
{
  DPRINT("visiting Job");
  //TODO build JShellJob and execute
  switch(p->kind)
  }
  case is_AssigJob:
    DPRINT("is AssigJob");

    visitShellToken(p->u.assigJob_.shelltoken_);
    visitCommandLine(p->u.assigJob_.commandline_);
    break;
  case is_FGJob:
    /* Code for FGJob Goes Here */
    DPRINT("is FGJob");
    visitCommandLine(p->u.fGJob_.commandline_);
    break;
  case is_BGJob:
    /* Code for BGJob Goes Here */
    DPRINT("is BGJob");
    visitCommandLine(p->u.bGJob_.commandline_);
    break;
  case is_AIChatJob:
    /* Code for AIChatJob Goes Here */
    DPRINT("is AIChatJob");
    visitAIQueryToken(p->u.aIChatJob_.aiquerytoken_);
    break;
  case is_AIExecJob:
    /* Code for AIExecJob Goes Here */
    DPRINT("is AIExecJob");
    visitAIExecToken(p->u.aIExecJob_.aiexectoken_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Job!\n");
    exit(1);
  }
}

void visitCommandLine(CommandLine p)
{
  DPRINT("visiting CommandLine");

  // TODO: Build and return cmd_vector
  JShellCmdVector jshell_cmd_vector;

  switch(p->kind)
  {
  case is_CmdLine:
    visitCommandPart(p->u.cmdLine_.commandpart_);
    visitOptionalInputRedirection(p->u.cmdLine_.optionalinputredirection_);
    visitOptionalOutputRedirection(p->u.cmdLine_.optionaloutputredirection_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandLine!\n");
    exit(1);
  }
}

void visitCommandPart(CommandPart p)
{
  DPRINT("visiting CommandPart");
  int cmd_count = 0;

  switch(p->kind)
  {
  case is_SnglCmd:
    /* Code for SnglCmd Goes Here */
    DPRINT("is SnglCmd");
    visitCommandUnit(p->u.snglCmd_.commandunit_);
    break;
  case is_PipeCmd:
    /* Code for PipeCmd Goes Here */
    DPRINT("is PipeCmd");
    visitCommandUnit(p->u.pipeCmd_.commandunit_);
    visitCommandPart(p->u.pipeCmd_.commandpart_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandPart!\n");
    exit(1);
  }
}

void visitOptionalInputRedirection(OptionalInputRedirection p)
{
  DPRINT("visiting OptionalInputRedirection");

  wordexp_t word_vector = {0};

  switch(p->kind)
  {
  case is_NoInRedir:
    /* Code for NoInRedir Goes Here */
    DPRINT("is NoInRedir");
    break;
  case is_InRedir:
    /* Code for InRedir Goes Here */
    DPRINT("is InRedir");
    int result = visitShellToken(p->u.inRedir_.shelltoken_, &word_vector);
    DPRINT("wordexp result: %d", result);
    DPRINT_WORDEXP(word_vector);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptionalInputRedirection!\n");
    exit(1);
  }
}

void visitOptionalOutputRedirection(OptionalOutputRedirection p)
{
  DPRINT("visiting OptionalOutputRedirection");

  wordexp_t word_vector = {0};

  switch(p->kind)
  {
  case is_NoOutRedir:
    /* Code for NoOutRedir Goes Here */
    DPRINT("is NoOutRedir");
    break;
  case is_OutRedir:
    /* Code for OutRedir Goes Here */
    DPRINT("is OutRedir");
    int result = visitShellToken(p->u.outRedir_.shelltoken_, &word_vector);
    DPRINT("wordexp result: %d", result);
    DPRINT_WORDEXP(word_vector);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptionalOutputRedirection!\n");
    exit(1);
  }

}

JshellCmdParams visitCommandUnit(CommandUnit p)
{
  DPRINT("visiting CommandUnit");

  wordexp_t word_vector = {0};

  switch(p->kind)
  {
  case is_CmdUnit:

    int result = visitListShellToken(p->u.cmdUnit_.listshelltoken_, &word_vector);

    DPRINT("wordexp result: %d", result);
    DPRINT_WORDEXP(word_vector);

    JshellCmdParams cmd_params = {
      .argc = (int)word_vector.we_wordc,
      .argv = word_vector.we_wordv
    };
    return cmd_params;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandUnit!\n");
    exit(1);
  }
}

int visitListShellToken(ListShellToken listshelltoken, wordexp_t* word_vector_ptr)
{
  DPRINT("visiting ListShellToken");

  int wordexp_result = 0;

  while(listshelltoken  != 0)
  {
    wordexp_result = visitShellToken(listshelltoken->shelltoken_, word_vector_ptr);
    // return wordexp_result if it is nonzero
    if (wordexp_result != 0) {
      return wordexp_result;
    }

    listshelltoken = listshelltoken->listshelltoken_;
  }
  return wordexp_result;
}


int visitShellToken(ShellToken p, wordexp_t* word_vector_ptr)
{
  DPRINT("visiting ShellToken");

  switch(p->kind)
  {
  case is_ExpStr:
    return visitExpansionStringToken(p->u.expStr_.expansionstringtoken_, word_vector_ptr);
    break;
  case is_LitStr:
    return visitLiteralStringToken(p->u.litStr_.literalstringtoken_, word_vector_ptr);
    break;
  case is_Var:
    return visitVariableToken(p->u.var_.variabletoken_, word_vector_ptr);
    break;
  case is_Wrd:
    return visitWordToken(p->u.wrd_.wordtoken_, word_vector_ptr);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ShellToken!\n");
    exit(1);
  }
}

int visitExpansionStringToken(ExpansionStringToken p, wordexp_t* word_vector_ptr)
{
  DPRINT("visiting ExpansionStringToken");
  return jshell_expand_word(p, word_vector_ptr);
}
int visitLiteralStringToken(LiteralStringToken p, wordexp_t* word_vector_ptr)
{
  DPRINT("visiting LiteralStringToken");
  return jshell_expand_word(p, word_vector_ptr);
}
int visitVariableToken(VariableToken p, wordexp_t* word_vector_ptr)
{
  DPRINT("visiting VariableToken");
  return jshell_expand_word(p, word_vector_ptr);
}
int visitWordToken(WordToken p, wordexp_t* word_vector_ptr)
{
  DPRINT("visiting WordToken");
  return jshell_expand_word(p, word_vector_ptr);
}


void visitAIQueryToken(AIQueryToken p)
{
  DPRINT("visiting AIQueryToken");
  /* Code for AIQueryToken Goes Here */
}
void visitAIExecToken(AIExecToken p)
{
  DPRINT("visiting AIExecToken");
  /* Code for AIExecToken Goes Here */
}


// TODO: Trim Fat
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}
